# Generated by Django 4.2.3 on 2023-07-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashuser',
            name='full_name',
            field=models.CharField(default='Andriy Melnik', max_length=100),
            preserve_default=False,
        ),
    ]
