# Generated by Django 4.2.3 on 2023-07-16 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flash_app', '0002_flashuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='flash_app.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='./images/posts/default.png', upload_to='', verbose_name='./images/posts'),
        ),
        migrations.AlterField(
            model_name='flashuser',
            name='avatar',
            field=models.ImageField(default='./images/avatars/default.png', upload_to='./images/avatars'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to='flash_app.like'),
        ),
    ]
