# Generated by Django 4.2.3 on 2023-07-17 07:24

from django.db import migrations, models
import flash_app.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('flash_app', '0003_post_comments_post_images_alter_flashuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='flashuser',
            managers=[
                ('objects', flash_app.models.user.FlashUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='flashuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='flashuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='flashuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='flashuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='flashuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='flashuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='flashuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='flashuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='flashuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='flashuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
