# Generated by Django 4.2.3 on 2023-07-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_app', '0005_flashuser_date_joined_flashuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashuser',
            name='bio',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='flashuser',
            name='full_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='flashuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(default='./images/posts/default.png', upload_to='', verbose_name='./'),
        ),
    ]
