# Generated by Django 4.2.3 on 2023-07-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_app', '0006_flashuser_bio_alter_flashuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=2500),
        ),
    ]
