# Generated by Django 4.2.3 on 2023-07-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_app', '0007_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='flashuser',
            name='bio',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='flashuser',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
