# Generated by Django 4.2.3 on 2023-07-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_app', '0010_follower_follower_alter_follower_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
    ]
