# Generated by Django 4.2.3 on 2023-07-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flash_app', '0013_follower_follower_alter_follower_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
